// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pull_requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPullRequest = `-- name: CreatePullRequest :exec
INSERT INTO pull_requests (pull_request_id, pull_request_name, author_id)
VALUES ($1, $2, $3)
`

type CreatePullRequestParams struct {
	PullRequestID   string
	PullRequestName string
	AuthorID        string
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) error {
	_, err := q.db.ExecContext(ctx, createPullRequest, arg.PullRequestID, arg.PullRequestName, arg.AuthorID)
	return err
}

const getPullRequest = `-- name: GetPullRequest :one
SELECT pull_request_id, pull_request_name, author_id, status, created_at, merged_at FROM pull_requests WHERE pull_request_id = $1
`

func (q *Queries) GetPullRequest(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPullRequest, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const getPullRequestShortByReviewer = `-- name: GetPullRequestShortByReviewer :many
SELECT pr.pull_request_id, pr.pull_request_name, pr.author_id, pr.status
FROM pull_requests pr
JOIN pull_request_reviewers ar USING(pull_request_id)
WHERE ar.reviewer_id = $1
`

type GetPullRequestShortByReviewerRow struct {
	PullRequestID   string
	PullRequestName string
	AuthorID        string
	Status          PrStatus
}

func (q *Queries) GetPullRequestShortByReviewer(ctx context.Context, reviewerID uuid.UUID) ([]GetPullRequestShortByReviewerRow, error) {
	rows, err := q.db.QueryContext(ctx, getPullRequestShortByReviewer, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPullRequestShortByReviewerRow
	for rows.Next() {
		var i GetPullRequestShortByReviewerRow
		if err := rows.Scan(
			&i.PullRequestID,
			&i.PullRequestName,
			&i.AuthorID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergePullRequest = `-- name: MergePullRequest :one
UPDATE pull_requests
SET status = 'MERGED', merged_at = NOW()
WHERE pull_request_id = $1
RETURNING pull_request_id, pull_request_name, author_id, status, created_at, merged_at
`

func (q *Queries) MergePullRequest(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, mergePullRequest, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}
