// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reviewers.sql

package db

import (
	"context"
)

const assignReviewer = `-- name: AssignReviewer :exec
INSERT INTO pull_request_reviewers (pull_request_id, reviewer_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignReviewerParams struct {
	PullRequestID string
	ReviewerID    string
}

func (q *Queries) AssignReviewer(ctx context.Context, arg AssignReviewerParams) error {
	_, err := q.db.ExecContext(ctx, assignReviewer, arg.PullRequestID, arg.ReviewerID)
	return err
}

const deleteReviewer = `-- name: DeleteReviewer :exec
DELETE FROM pull_request_reviewers
WHERE pull_request_id = $1 AND reviewer_id = $2
`

type DeleteReviewerParams struct {
	PullRequestID string
	ReviewerID    string
}

func (q *Queries) DeleteReviewer(ctx context.Context, arg DeleteReviewerParams) error {
	_, err := q.db.ExecContext(ctx, deleteReviewer, arg.PullRequestID, arg.ReviewerID)
	return err
}

const getReviewers = `-- name: GetReviewers :many
SELECT reviewer_id FROM pull_request_reviewers
WHERE pull_request_id = $1
ORDER BY reviewer_id
`

func (q *Queries) GetReviewers(ctx context.Context, pullRequestID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getReviewers, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var reviewer_id string
		if err := rows.Scan(&reviewer_id); err != nil {
			return nil, err
		}
		items = append(items, reviewer_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isReviewerAssigned = `-- name: IsReviewerAssigned :one
SELECT reviewer_id FROM pull_request_reviewers WHERE pull_request_id = $1 AND reviewer_id = $2
`

type IsReviewerAssignedParams struct {
	PullRequestID string
	ReviewerID    string
}

func (q *Queries) IsReviewerAssigned(ctx context.Context, arg IsReviewerAssignedParams) (string, error) {
	row := q.db.QueryRowContext(ctx, isReviewerAssigned, arg.PullRequestID, arg.ReviewerID)
	var reviewer_id string
	err := row.Scan(&reviewer_id)
	return reviewer_id, err
}
