// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reviewers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignReviewer = `-- name: AssignReviewer :exec
INSERT INTO pull_request_reviewers (pull_request_id, reviewer_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignReviewerParams struct {
	PullRequestID uuid.UUID
	ReviewerID    uuid.UUID
}

func (q *Queries) AssignReviewer(ctx context.Context, arg AssignReviewerParams) error {
	_, err := q.db.ExecContext(ctx, assignReviewer, arg.PullRequestID, arg.ReviewerID)
	return err
}

const deleteReviewer = `-- name: DeleteReviewer :exec
DELETE FROM pull_request_reviewers
WHERE pull_request_id = $1 AND reviewer_id = $2
`

type DeleteReviewerParams struct {
	PullRequestID uuid.UUID
	ReviewerID    uuid.UUID
}

func (q *Queries) DeleteReviewer(ctx context.Context, arg DeleteReviewerParams) error {
	_, err := q.db.ExecContext(ctx, deleteReviewer, arg.PullRequestID, arg.ReviewerID)
	return err
}

const getReviewers = `-- name: GetReviewers :many
SELECT reviewer_id FROM pull_request_reviewers
WHERE pull_request_id = $1
`

func (q *Queries) GetReviewers(ctx context.Context, pullRequestID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getReviewers, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var reviewer_id uuid.UUID
		if err := rows.Scan(&reviewer_id); err != nil {
			return nil, err
		}
		items = append(items, reviewer_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
