// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: statistics.sql

package db

import (
	"context"
)

const getPRsWithoutReview = `-- name: GetPRsWithoutReview :one
SELECT COUNT(*) AS no_review_count
FROM pull_requests pr
LEFT JOIN pull_request_reviewers r 
    ON pr.pull_request_id = r.pull_request_id
WHERE r.reviewer_id IS NULL
  AND pr.status = 'OPEN'
`

func (q *Queries) GetPRsWithoutReview(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPRsWithoutReview)
	var no_review_count int64
	err := row.Scan(&no_review_count)
	return no_review_count, err
}

const getReviewStatsByUser = `-- name: GetReviewStatsByUser :many
SELECT reviewer_id, COUNT(*) AS reviews_count
FROM pull_request_reviewers
GROUP BY reviewer_id
`

type GetReviewStatsByUserRow struct {
	ReviewerID   string
	ReviewsCount int64
}

func (q *Queries) GetReviewStatsByUser(ctx context.Context) ([]GetReviewStatsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getReviewStatsByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewStatsByUserRow
	for rows.Next() {
		var i GetReviewStatsByUserRow
		if err := rows.Scan(&i.ReviewerID, &i.ReviewsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
