// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams (team_name) VALUES ($1)
`

func (q *Queries) CreateTeam(ctx context.Context, teamName string) error {
	_, err := q.db.ExecContext(ctx, createTeam, teamName)
	return err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT u.user_id, u.username, u.is_active
FROM users u
WHERE u.team_name = $1
`

type GetTeamMembersRow struct {
	UserID   uuid.UUID
	Username string
	IsActive bool
}

func (q *Queries) GetTeamMembers(ctx context.Context, teamName string) ([]GetTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembers, teamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersRow
	for rows.Next() {
		var i GetTeamMembersRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
