// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getActiveReplacementCandidates = `-- name: GetActiveReplacementCandidates :many
SELECT u.user_id
FROM users u
WHERE u.team_name = (
    SELECT inner_u.team_name FROM users inner_u WHERE inner_u.user_id = $1
)
AND u.is_active = TRUE
AND u.user_id <> $1
`

func (q *Queries) GetActiveReplacementCandidates(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveReplacementCandidates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTeamReviewCandidates = `-- name: GetActiveTeamReviewCandidates :many
SELECT u.user_id
FROM users u
WHERE u.team_name = $1
  AND u.is_active = TRUE
  AND u.user_id <> $2
`

type GetActiveTeamReviewCandidatesParams struct {
	TeamName string
	UserID   string
}

func (q *Queries) GetActiveTeamReviewCandidates(ctx context.Context, arg GetActiveTeamReviewCandidatesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTeamReviewCandidates, arg.TeamName, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, team_name, is_active FROM users WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users
SET is_active = $2
WHERE user_id = $1
RETURNING user_id, username, team_name, is_active
`

type SetUserActiveParams struct {
	UserID   string
	IsActive bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserActive, arg.UserID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (user_id, username, team_name, is_active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET username = excluded.username,
    team_name = excluded.team_name,
    is_active = excluded.is_active
`

type UpsertUserParams struct {
	UserID   string
	Username string
	TeamName string
	IsActive bool
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.UserID,
		arg.Username,
		arg.TeamName,
		arg.IsActive,
	)
	return err
}
