// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, username, team_name, is_active FROM users WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users
SET is_active = $2
WHERE user_id = $1
RETURNING user_id, username, team_name, is_active
`

type SetUserActiveParams struct {
	UserID   string
	IsActive bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserActive, arg.UserID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (user_id, username, team_name, is_active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET username = excluded.username,
    team_name = excluded.team_name,
    is_active = excluded.is_active
`

type UpsertUserParams struct {
	UserID   string
	Username string
	TeamName string
	IsActive bool
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.UserID,
		arg.Username,
		arg.TeamName,
		arg.IsActive,
	)
	return err
}
